### PR TITLE
Nimbix menu and panel fix

### PR DESCRIPTION
**Pull request by schrummy14**
Contains commits from the other two pull requests.

### CODE REVIEW

**Comment by schrummy14** [comment]
Hold on the pull request.
I used the latest changes on the newest ParaView app, and Qorvo is complaining about how they now need to enter a password to get into the app. How this is caused by the new changes to jarvice-desktop? No idea, but better to double-check... These issues are not verifiable on `cloud.nimbix.net` or `federated.nimbix.net`.

**Comment by schrummy14** [comment]
Ready for merge

**Comment by schrummy14** [comment]
Will need a different pull request for tiger VNC updates. Cannot use the latest version from the OS's repo as there are breaking changes.

**Review by oxedions — APPROVED** [review]
Nice work !! :blush:

**Pull request merged**
